### ISSUE TITLE
Error installing on ubuntu 14.04: "cannot download, $GOPATH not set"

### ISSUE THREAD

**Issue by barbalex** [rakyll/drive#13]
I did:

```
sudo apt-get install golang git mercurial
go get github.com/rakyll/drive
```

Then got:
"package github.com/rakyll/drive: cannot download, $GOPATH not set. For more details see: go help gopath"

go version is: "go1.2.1 linux/amd64"

**Comment by stefanoschrs** [comment]
@rogerthomas84 This trick worked for me! Thanks a lot

**Comment by lyma** [comment]
Still works! ;)

**Comment by spicebits** [comment]
@rogerthomas84 : the same thing is not working for me :(

**Comment by kaarla** [comment]
@rohitcyablord how did you fixed it? :(

**Comment by conncui** [comment]
> @barbalex this might help you:
> 
> ```shell
> $ mkdir /path/to/a/folder
> ```
> 
> Then add this to `~/.bashrc`
> 
> ```shell
> export GOPATH=/path/to/a/folder
> ```
> 
> Finally, source the changes:
> 
> ```shell
> $ source ~/.bashrc
> ```
> 
> Try it again. Should work.

GOPATH not mean path refer go installed dir， but your go-lib dir

**Comment by barbalex** [comment]
@conncui thanks. As I have moved on (https://github.com/rakyll/drive/issues/13#issuecomment-61495007) your answer might help others
